title: Consortium for Clinical Research and Innovation, Singapore (CRIS)
url: https://cris.sg
favicon: /images/Favicon.png
colors:
  primary-color: "#002856"
  secondary-color: "#3dc5f3"
  media-colors:
    - title: media-color-one
      color: "#583f98"
    - title: media-color-two
      color: "#002856"
    - title: media-color-three
      color: "#ef4f23"
    - title: media-color-four
      color: "#3dc5f3"
    - title: media-color-five
      color: "#002856"
description: The Consortium for Clinical Research and Innovation Singapore
  (CRIS) strengthens synergies and develops strategies for national clinical
  research and translation programmes that are under the stewardship of the
  Ministry of Health.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d278onkulfqe8r.amplifyapp.com
prod: https://master.d278onkulfqe8r.amplifyapp.com
shareicon: /images/Logos/CRIS.png
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: news-and-events
